### PR TITLE
Add myself to the members!

### PR DESCRIPTION
**Pull request by ramonh**

### CODE REVIEW

**Comment by geraldb** [comment]
Welcome. Thanks. Cheers. PS: Note: It's optional - You will also get an invitation (by email from GitHub) to join the Vienna.html org as a member. If you accept, you can edit the members.yml file in your browser - no longer any need for a pull request - and you will show up in the people page too (if you set your preference to public - default is private)

**Comment by ramonh** [comment]
Thank you, Gerald! highly looking forward to it. Where can I set this public preference? In the members.yml file?



—
Ramón Huidobro



http://ramonhuidobro.com

**Comment by geraldb** [comment]
Welcome. Sorry for the missing link. See the [github org people page](https://github.com/orgs/viennahtml/people).

**Comment by ramonh** [comment]
Ah, makes sense. My mistake! Thank you @geraldb!

**Pull request merged**
