### PR TITLE
Add @karlhorky

### PR DESCRIPTION
**Pull request by karlhorky**

### CODE REVIEW

**Comment by geraldb** [comment]
@karlhorky Fantastic. Welcome. Thanks. Cheers. PS:  Note: It's optional - You will also get an invitation (by email from GitHub) to join the Vienna.html org as a member. If you accept, you can edit the members.yml file in your browser - no longer any need for a pull request - and you will show up in the people page too (if you set your preference to public - default is private).     PS: There's a merge conflict - will add your additions "by hand". Welcome again.

**Comment by karlhorky** [comment]
Thanks @geraldb. I've become a member.

**Comment by geraldb** [comment]
Welcome.  FYI: First Vienna.html meetup on Nov Tue 24th @ Sektor 5 starting at 18.30.

**Comment by karlhorky** [comment]
Nice, thanks for the heads up.

**Pull request closed without merging**
